name: publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # curseneoforge-id: 123456
          # curseneoforge-token: "${{ secrets.CURSEneoforge_TOKEN }}"

          modrinth-id: 6DnswkCZ
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "Hey Wiki ${{ github.ref_name }} for Minecraft ${{ env.MINECRAFT_VERSION }}"
          version: "${{ github.ref_name }}+${{ env.MINECRAFT_VERSION }}"
          version-type: release
          changelog-file: CHANGELOG.md
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/