name: publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  JAVA_VERSION: 21

jobs:
  properties:
    # Read gradle.properties and get snapshot property
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: read gradle.properties
        id: gradle-properties
        run: |
          echo "snapshot=$(grep '^snapshot=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "minecraft_version=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
  build:
    needs: properties
    strategy:
      fail-fast: false
      matrix:
        loader:
          - name: fabric
            formatted: Fabric
          - name: neoforge
            formatted: NeoForge
        exclude:
          - loader:
              name: ${{ needs.properties.outputs.snapshot == 'true' && 'neoforge' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: "${{ runner.os }}-jdk${{ env.JAVA_VERSION }}"
          arguments: "${{ matrix.loader.name }}:build"
          gradle-version: wrapper
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 997027
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          modrinth-id: 6DnswkCZ
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "Hey Wiki ${{ github.ref_name }} for Minecraft ${{ needs.properties.outputs.snapshot }} with ${{ matrix.loader.formatted }}"
          version: "${{ github.ref_name }}+${{ needs.properties.outputs.snapshot }}+${{ matrix.loader.name }}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: ${{ matrix.loader.name }}
          files: ${{ matrix.loader.name }}/build/libs/!(*-sources|*-dev-shadow).jar
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ${{ matrix.loader.name }}/build/libs/