name: publish

on: [ release, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # curseforge-id: 123456
          # curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"

          modrinth-id: 6DnswkCZ
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          github-token: "${{ env.GITHUB_TOKEN }}"

          name: "Hey Wiki ${{ env.GITHUB_REF }} for Minecraft ${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.GITHUB_REF }}+${{ env.MINECRAFT_VERSION }}"
          version-type: release
          changelog-file: CHANGELOG.md
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/